name: Rodrigo Teixeira

description: Product & Service Designer

avatar: https://media.licdn.com/mpr/mpr/shrink_200_200/p/2/005/037/0b0/3d3e4b9.jpg

disqus: drigoteixeira

google_analytics: UA-32844537-1

url: https://www.rodrigoteixeira.co

baseurl: ""

source: .

header-img: https://rodrigoteixeira.co/img/cover.jpg

destination: ./_site
plugins_dir: ./_plugins

# Build settings
markdown: kramdown
permalink: pretty

syntax-highlighting:
   enabled : true
   css: highlight.css

kramdown:
  input: GFM
  syntax_highlighter: rouge

# PAGINATION
permalink: blog/:title/
paginate: 10
paginate_path: 'blog/page:num'

version: v1.0.0

sass:
  sass_dir: _scss
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
